blank_issues_enabled: true
contact_links:
  - name: Support requests and Troubleshooting
    url: https://tailscale.com/kb/1023/troubleshooting
    about: Troubleshoot common issues. Contact us by email at support@tailscale.com.